name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Autograding
      id: autograding
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 1
        max-score: 1
        setup-command: pip install pytest
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        AUTOGRADING_RESULTS: "${{steps.autograding.outputs.result}}"
      with:
        runners: autograding
